!!python/object:ml_collections.config_dict.config_dict.ConfigDict
_convert_dict: true
_fields:
  benchmark: false
  callbacks:
  - !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      class_path: vis4d.engine.callbacks.logging.LoggingCallback
      init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          epoch_based: true
          refresh_rate: 50
        _locked: false
        _type_safe: true
    _locked: false
    _type_safe: true
  - !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      class_path: vis4d.engine.callbacks.checkpoint.CheckpointCallback
      init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          checkpoint_period: 1
          epoch_based: true
          save_prefix: vis4d-workspace/velo_lstm_frcnn_r101_fpn_100e_nusc/2023-07-31_21-12-02
        _locked: false
        _type_safe: true
    _locked: false
    _type_safe: true
  data: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      test_dataloader: null
      train_dataloader: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          class_path: vis4d.data.loader.build_train_dataloader
          init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
            _convert_dict: true
            _fields:
              batchprocess_fn: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                _convert_dict: true
                _fields:
                  class_path: vis4d.data.transforms.to_tensor.ToTensor
                _locked: false
                _type_safe: true
              collate_fn: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                _convert_dict: true
                _fields:
                  class_path: vis4d.config.config_dict.DelayedInstantiator
                  init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                    _convert_dict: true
                    _fields:
                      instantiable: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                        _convert_dict: true
                        _fields:
                          _class_path: vis4d.data.loader.default_collate
                        _locked: false
                        _type_safe: true
                    _locked: false
                    _type_safe: true
                _locked: false
                _type_safe: true
              collate_keys:
              - pred_traj
              - gt_traj
              dataset: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                _convert_dict: true
                _fields:
                  class_path: vis4d.data.data_pipe.DataPipe
                  init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                    _convert_dict: true
                    _fields:
                      datasets: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                        _convert_dict: true
                        _fields:
                          class_path: vis4d.data.datasets.nuscenes_trajectory.NuScenesTrajectory
                          init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                            _convert_dict: true
                            _fields:
                              cache_as_binary: true
                              cached_file_path: data/nuscenes/cc_3dt_frcnn_r101_fpn_traj_train.pkl
                              data_root: data/nuscenes
                              detector: cc_3dt_frcnn_r101_fpn
                              pure_detection: ./vis4d-workspace/pure_det/cc_3dt_frcnn_r101_fpn.json
                              split: train
                              version: v1.0-trainval
                            _locked: false
                            _type_safe: true
                        _locked: false
                        _type_safe: true
                    _locked: false
                    _type_safe: true
                _locked: false
                _type_safe: true
              pin_memory: true
              samples_per_gpu: 32
              sensors: null
              shuffle: true
              workers_per_gpu: 4
            _locked: false
            _type_safe: true
        _locked: false
        _type_safe: true
    _locked: false
    _type_safe: true
  experiment_name: velo_lstm_frcnn_r101_fpn_100e_nusc
  log_every_n_steps: 50
  loss: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      class_path: vis4d.engine.loss_module.LossModule
      init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          losses:
          - connector: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
              _convert_dict: true
              _fields:
                class_path: vis4d.engine.connectors.base.LossConnector
                init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                  _convert_dict: true
                  _fields:
                    key_mapping: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                      _convert_dict: true
                      _fields:
                        gt_traj: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                          _convert_dict: true
                          _fields:
                            key: gt_traj
                            source: data
                          _locked: false
                          _type_safe: true
                        loc_preds: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                          _convert_dict: true
                          _fields:
                            key: loc_preds
                            source: prediction
                          _locked: false
                          _type_safe: true
                        loc_refines: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                          _convert_dict: true
                          _fields:
                            key: loc_refines
                            source: prediction
                          _locked: false
                          _type_safe: true
                      _locked: false
                      _type_safe: true
                  _locked: false
                  _type_safe: true
              _locked: false
              _type_safe: true
            loss: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
              _convert_dict: true
              _fields:
                class_path: vis4d.op.motion.velo_lstm.VeloLSTMLoss
              _locked: false
              _type_safe: true
        _locked: false
        _type_safe: true
    _locked: false
    _type_safe: true
  model: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      class_path: vis4d.model.motion.velo_lstm.VeloLSTM
    _locked: false
    _type_safe: true
  optimizers:
  - !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      lr_schedulers:
      - !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          begin: 0
          convert_attributes: null
          convert_epochs_to_steps: false
          end: -1
          epoch_based: true
          scheduler: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
            _convert_dict: true
            _fields:
              class_path: torch.optim.lr_scheduler.MultiStepLR
              init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
                _convert_dict: true
                _fields:
                  gamma: 0.5
                  milestones:
                  - 20
                  - 40
                  - 60
                  - 80
                _locked: false
                _type_safe: true
            _locked: false
            _type_safe: true
        _locked: false
        _type_safe: true
      optimizer: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          class_path: torch.optim.adam.Adam
          init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
            _convert_dict: true
            _fields:
              amsgrad: true
              lr: 0.005
              weight_decay: 0.0001
            _locked: false
            _type_safe: true
        _locked: false
        _type_safe: true
      param_groups: null
    _locked: false
    _type_safe: true
  output_dir: vis4d-workspace/velo_lstm_frcnn_r101_fpn_100e_nusc/2023-07-31_21-12-02
  params: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      lr: 0.005
      num_epochs: 100
      samples_per_gpu: 32
      workers_per_gpu: 4
    _locked: false
    _type_safe: true
  pl_callbacks: []
  pl_trainer: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      accelerator: auto
      accumulate_grad_batches: 1
      barebones: false
      benchmark: false
      check_val_every_n_epoch: 101
      checkpoint_period: 1
      default_root_dir: null
      detect_anomaly: false
      deterministic: null
      enable_checkpointing: null
      enable_model_summary: null
      enable_progress_bar: false
      exp_name: velo_lstm_frcnn_r101_fpn_100e_nusc
      fast_dev_run: false
      find_unused_parameters: false
      gradient_clip_algorithm: null
      gradient_clip_val: 3
      inference_mode: true
      limit_predict_batches: null
      limit_test_batches: null
      limit_train_batches: null
      limit_val_batches: null
      log_every_n_steps: 50
      max_epochs: 100
      max_steps: -1
      max_time: null
      min_epochs: null
      min_steps: null
      num_nodes: 1
      num_sanity_val_steps: 0
      overfit_batches: 0.0
      plugins: null
      precision: 32-true
      profiler: null
      reload_dataloaders_every_n_epochs: 0
      save_top_k: 1
      sync_batchnorm: false
      use_distributed_sampler: false
      val_check_interval: null
      version: 2023-07-31_21-12-02
      wandb: false
      work_dir: vis4d-workspace
    _locked: false
    _type_safe: true
  seed: -1
  test_data_connector: null
  timestamp: 2023-07-31_21-12-02
  train_data_connector: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      class_path: vis4d.engine.connectors.base.DataConnector
      init_args: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          key_mapping: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
            _convert_dict: true
            _fields:
              pred_traj: pred_traj
            _locked: false
            _type_safe: true
        _locked: false
        _type_safe: true
    _locked: false
    _type_safe: true
  use_tf32: false
  version: 2023-07-31_21-12-02
  work_dir: vis4d-workspace
_locked: false
_type_safe: true
